// Unit tests for the codex → claude-stream-json translators (#1088). These run
// with `npm test` (node --test) and need no API key or codex binary — the
// translators are pure. The shapes asserted here are load-bearing for
// applyEventMeta (Go) and the dashboard transcript parser; see
// drivers/codex-translate.mjs.
//
// Item fixtures follow the app-server v2 protocol as generated by
// `codex app-server generate-ts` on the PINNED @openai/codex (Dockerfile).

import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  approvalPolicyFor,
  classifyCodexError,
  codexErrorCode,
  initPayload,
  isToolItem,
  mapEffort,
  messagePayload,
  partialPayload,
  resultPayload,
  toolFailed,
  toolInputFor,
  toolNameFor,
  toolResultPayload,
  toolResultText,
  toolUsePayload,
  usagePayload,
} from '../drivers/codex-translate.mjs'

test('initPayload carries the thread id the CP round-trips as the resume handle', () => {
  const p = initPayload('019f9ffb-5e94-76f2-8d3c-e840ea1d56c7', 'gpt-5.6-sol')
  assert.equal(p.type, 'system')
  assert.equal(p.subtype, 'init')
  assert.equal(p.session_id, '019f9ffb-5e94-76f2-8d3c-e840ea1d56c7')
  assert.equal(p.model, 'gpt-5.6-sol')
  assert.equal(p.harness, 'codex')
})

test('initPayload never emits undefined for a missing thread id', () => {
  assert.equal(initPayload(null, null).session_id, '')
})

test('isToolItem separates tool items from message items', () => {
  for (const type of ['commandExecution', 'fileChange', 'mcpToolCall', 'dynamicToolCall', 'webSearch']) {
    assert.equal(isToolItem({ type }), true, type)
  }
  for (const type of ['agentMessage', 'reasoning', 'userMessage', 'todoList', 'error']) {
    assert.equal(isToolItem({ type }), false, type)
  }
  assert.equal(isToolItem(null), false)
})

test('bridged connector tools keep the mcp__slug__tool name the escalation gate matches', () => {
  // isEscalatedTool (server.mjs) matches this prefix on BOTH harnesses; a
  // rename here silently disables escalation for codex.
  // The WIRE name is what a dynamicToolCall item carries — codex reserves
  // mcp__, so bridged tools travel as zwrm__ — and the transcript must record
  // the canonical form. Feeding an already-canonical name here would pass with
  // or without the mapping.
  assert.equal(toolNameFor({ type: 'dynamicToolCall', tool: 'zwrm__github__create_issue' }), 'mcp__github__create_issue')
  assert.equal(toolNameFor({ type: 'mcpToolCall', server: 'github', tool: 'create_issue' }), 'mcp__github__create_issue')
})

test('toolNameFor maps codex-native items to stable names', () => {
  assert.equal(toolNameFor({ type: 'commandExecution' }), 'shell')
  assert.equal(toolNameFor({ type: 'fileChange' }), 'apply_patch')
  assert.equal(toolNameFor({ type: 'webSearch' }), 'web_search')
})

test('toolInputFor surfaces what an approval reviewer needs to see', () => {
  assert.deepEqual(
    toolInputFor({ type: 'commandExecution', command: 'rm -rf /tmp/x', cwd: '/home/agent' }),
    { command: 'rm -rf /tmp/x', cwd: '/home/agent' },
  )
  assert.deepEqual(
    toolInputFor({ type: 'fileChange', changes: [{ path: 'a.go', kind: 'update', diff: '...' }] }),
    { changes: [{ path: 'a.go', kind: 'update' }] },
  )
  assert.deepEqual(toolInputFor({ type: 'mcpToolCall', arguments: { n: 1 } }), { n: 1 })
})

test('toolUsePayload renders a claude tool_use block keyed by the item id', () => {
  const p = toolUsePayload({ type: 'commandExecution', id: 'item_1', command: 'ls', cwd: '/w' }, 'gpt-5.6-sol')
  assert.equal(p.type, 'assistant')
  assert.deepEqual(p.message.content, [
    { type: 'tool_use', id: 'item_1', name: 'shell', input: { command: 'ls', cwd: '/w' } },
  ])
})

test('toolResultPayload pairs with the tool_use via tool_use_id', () => {
  const p = toolResultPayload({
    type: 'commandExecution', id: 'item_1', status: 'completed', aggregatedOutput: 'a.go\n', exitCode: 0,
  })
  assert.equal(p.type, 'user')
  assert.deepEqual(p.message.content, [{ type: 'tool_result', tool_use_id: 'item_1', content: 'a.go\n' }])
})

test('a non-zero exit marks the tool_result as an error and keeps the code visible', () => {
  const item = { type: 'commandExecution', id: 'i', status: 'failed', aggregatedOutput: 'boom', exitCode: 2 }
  assert.equal(toolFailed(item), true)
  assert.equal(toolResultText(item), 'boom\n(exit code 2)')
  assert.equal(toolResultPayload(item).message.content[0].is_error, true)
})

test('a declined command reads as an error, not a silent success', () => {
  assert.equal(toolFailed({ type: 'commandExecution', status: 'declined' }), true)
})

test('mcpToolCall results flatten to text; errors surface their message', () => {
  assert.equal(
    toolResultText({ type: 'mcpToolCall', result: { content: [{ type: 'text', text: 'ok' }] } }),
    'ok',
  )
  const failed = { type: 'mcpToolCall', status: 'failed', error: { message: 'upstream 500' } }
  assert.equal(toolResultText(failed), 'upstream 500')
  assert.equal(toolFailed(failed), true)
})

test('dynamicToolCall output maps text content items and honours success=false', () => {
  const item = {
    type: 'dynamicToolCall', id: 'd1', tool: 'mcp__github__list', success: false,
    contentItems: [{ type: 'inputText', text: 'denied' }, { type: 'inputImage', imageUrl: 'x' }],
  }
  assert.equal(toolResultText(item), 'denied')
  assert.equal(toolFailed(item), true)
})

test('messagePayload maps agentMessage to text and reasoning to thinking', () => {
  const m = messagePayload({ type: 'agentMessage', id: 'a', text: 'done' }, 'gpt-5.6-sol')
  assert.deepEqual(m.message.content, [{ type: 'text', text: 'done' }])
  const r = messagePayload({ type: 'reasoning', id: 'r', summary: ['step one'], content: ['raw'] }, '')
  assert.deepEqual(r.message.content, [{ type: 'thinking', thinking: 'step one' }])
})

test('reasoning falls back to raw content when there is no summary', () => {
  const r = messagePayload({ type: 'reasoning', id: 'r', summary: [], content: ['raw'] }, '')
  assert.deepEqual(r.message.content, [{ type: 'thinking', thinking: 'raw' }])
})

test('partialPayload emits the exact shape partialTextDelta reads', () => {
  const p = partialPayload({ delta: 'hel' })
  assert.equal(p.type, 'stream_event')
  assert.equal(p.event.type, 'content_block_delta')
  assert.deepEqual(p.event.delta, { type: 'text_delta', text: 'hel' })
})

test('partialPayload drops empty and non-string deltas', () => {
  assert.equal(partialPayload({ delta: '' }), null)
  assert.equal(partialPayload({}), null)
  assert.equal(partialPayload(null), null)
})

test('usagePayload maps codex token names onto the claude usage fields', () => {
  assert.deepEqual(
    usagePayload({ totalTokens: 30, inputTokens: 10, cachedInputTokens: 4, outputTokens: 20, reasoningOutputTokens: 5 }),
    { input_tokens: 10, output_tokens: 20, cache_read_input_tokens: 4, cache_creation_input_tokens: 0 },
  )
  assert.equal(usagePayload(null), undefined)
})

test('resultPayload always reports zero cost — codex sessions are unmetered', () => {
  // The CP banks GREATEST-diffs per session row (AccrueAgentSessionCost); a
  // constant 0 must accrue nothing. #1089 chose an unpriced catalog.
  const p = resultPayload({ resultText: 'MARKER', usage: { inputTokens: 1, outputTokens: 2 }, numTurns: 1, durationMS: 42 })
  assert.equal(p.type, 'result')
  assert.equal(p.subtype, 'success')
  assert.equal(p.result, 'MARKER')
  assert.equal(p.total_cost_usd, 0)
  assert.equal(p.duration_ms, 42)
  assert.deepEqual(p.usage, { input_tokens: 1, output_tokens: 2, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 })
})

test('a failed turn still produces a result — it is the run-completion gate', () => {
  const p = resultPayload({ subtype: 'error_during_execution', resultText: 'turn failed' })
  assert.equal(p.subtype, 'error_during_execution')
  assert.equal(p.is_error, true)
  assert.equal(p.total_cost_usd, 0)
})

test('codexErrorCode reads both CodexErrorInfo spellings', () => {
  assert.equal(codexErrorCode('unauthorized'), 'unauthorized')
  assert.equal(codexErrorCode({ httpConnectionFailed: { httpStatusCode: 503 } }), 'httpConnectionFailed')
  assert.equal(codexErrorCode(null), '')
})

test('classifyCodexError keys off the typed error before string matching', () => {
  const auth = classifyCodexError(Object.assign(new Error('nope'), { data: 'unauthorized' }))
  assert.equal(auth.cause, 'auth')
  assert.match(auth.message, /OPENAI_API_KEY/)

  const limited = classifyCodexError(Object.assign(new Error('nope'), { data: 'usageLimitExceeded' }))
  assert.equal(limited.cause, 'rate_limited')

  const ctx = classifyCodexError(Object.assign(new Error('too long'), { data: 'contextWindowExceeded' }))
  assert.equal(ctx.cause, 'error')
  assert.match(ctx.message, /context window/)

  const dead = classifyCodexError(Object.assign(new Error('exited'), { code: 'processExit' }))
  assert.equal(dead.cause, 'crashed')
})

test('classifyCodexError still falls back to string matching', () => {
  assert.equal(classifyCodexError(new Error('HTTP 429 rate limit')).cause, 'rate_limited')
  assert.equal(classifyCodexError(new Error('401 Unauthorized')).cause, 'auth')
  assert.equal(classifyCodexError(new Error('something else')).cause, 'error')
})

test('effort passes through the platform ladder without a model-blind clamp', () => {
  // 'max' is a REAL codex level on the gpt-5.6 family. Degrading it here (as
  // this driver did before the catalog existed) would downgrade every 5.6
  // session that asked for it, and would contradict the effort the control
  // plane already persisted on the run. Narrowing is the CP's job, because
  // only the CP knows which model was resolved.
  for (const e of ['low', 'medium', 'high', 'xhigh', 'max']) {
    assert.equal(mapEffort(e), e)
  }
  // Unrecognized levels are dropped, not forwarded: the app-server validates
  // nothing locally, so a typo would otherwise reach the API unchecked.
  assert.equal(mapEffort(''), undefined)
  assert.equal(mapEffort('nonsense'), undefined)
  // 'minimal' was a codex level once; no model in the pinned 0.145 lineup
  // offers it, so sending it would silently fall back to the model default.
  assert.equal(mapEffort('minimal'), undefined)
  // 'ultra' exists in codex but is not on the platform ladder, so the daemon
  // must never send it — exposing it is a platform-wide change, not a driver one.
  assert.equal(mapEffort('ultra'), undefined)
})

test('permission modes map onto codex approval + sandbox pairs', () => {
  assert.deepEqual(approvalPolicyFor('bypassPermissions'), { approvalPolicy: 'never', sandbox: 'danger-full-access' })
  assert.deepEqual(approvalPolicyFor('default'), { approvalPolicy: 'on-request', sandbox: 'workspace-write' })
})
